# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2253eb4c03baf331eb38d740a40a4f5ac9c0d68e1f67f7b4f22efbc3fd03d411115d7b021c1eb9ba1da36d14049d2298727f39cd0775a2408c13066ea2e05f8

test:
  secret_key_base: d86bb89912252f2e5bde4d40c918eb3ae9239129aff5127ea26b7736f22fbed8580d6f0695453d841bfae91e27026120205943f8a8409254d6b230e6cc4d7d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
